### ISSUE TITLE
Thrown items don't know who threw them

### ISSUE THREAD

**Issue by OmegaJak** [OmegaJak/Power_Drop#2]
This caused an issue with trying to tame rats (https://github.com/Alex-the-666/Rats/issues/136) from the Rats mod. When cheese was thrown, the cheese item didn't know who threw it, making rats untameable using Power Drop.

**Comment by OmegaJak** [comment]
Should be fixed in #3 (version 1.18.2-2.0.0) - more vanilla code is used after the rewrite now, including its code that sets the player that dropped the items.

**Comment by EliteMeats** [comment]
This bug is still present on the 1.12.2 version; could you please fix it on that version as well? Thanks

**Comment by OmegaJak** [comment]
Sure, I can look into that.

**Comment by OmegaJak** [comment]
Fixed in version 1.12.2-1.1.3

**Comment by EliteMeats** [comment]
Can confirm version 1.12.2-1.1.3 fixes this; it even works on other mobs like hippogryphs now. Thanks for the fix!
